# Generated by Django 4.0.5 on 2023-02-24 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0204_alter_idempotencecheck_time_created"),
    ]

    operations = [
        migrations.RenameModel("Plan", "PlanTemplate"),
    ]
