# Generated by Django 4.0.5 on 2023-02-24 20:42

from django.db import migrations, models
import metering_billing.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0205_auto_20230224_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalplan',
            name='addon_spec',
        ),
        migrations.RemoveField(
            model_name='historicalplan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalplan',
            name='display_version',
        ),
        migrations.RemoveField(
            model_name='historicalplan',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalplan',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='historicalplan',
            name='parent_plan',
        ),
        migrations.RemoveField(
            model_name='historicalplan',
            name='parent_product',
        ),
        migrations.RemoveField(
            model_name='historicalplan',
            name='target_customer',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='product',
            name='organization',
        ),
        migrations.RemoveIndex(
            model_name='plantemplate',
            name='metering_bi_organiz_b5d6d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='plantemplate',
            name='metering_bi_organiz_5f4b15_idx',
        ),
        migrations.RemoveIndex(
            model_name='planversion',
            name='metering_bi_organiz_847d79_idx',
        ),
        migrations.RemoveField(
            model_name='plantemplate',
            name='display_version',
        ),
        migrations.RemoveField(
            model_name='plantemplate',
            name='parent_product',
        ),
        migrations.RemoveField(
            model_name='plantemplate',
            name='status',
        ),
        migrations.AddField(
            model_name='historicalplanversion',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantemplate',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantemplate',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='plans', to='metering_billing.feature'),
        ),
        migrations.AddField(
            model_name='plantemplate',
            name='metrics',
            field=models.ManyToManyField(blank=True, related_name='plans', to='metering_billing.metric'),
        ),
        migrations.AddField(
            model_name='plantemplate',
            name='not_active_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantemplate',
            name='not_active_before',
            field=models.DateTimeField(blank=True, default=metering_billing.utils.utils.now_utc),
        ),
        migrations.AddField(
            model_name='planversion',
            name='customers',
            field=models.ManyToManyField(related_name='plan_versions', to='metering_billing.customer'),
        ),
        migrations.AddField(
            model_name='planversion',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='plan_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='plantemplate',
            index=models.Index(fields=['organization', 'plan_id'], name='metering_bi_organiz_659e0d_idx'),
        ),
        migrations.DeleteModel(
            name='HistoricalPlan',
        ),
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
