# Generated by Django 4.0.5 on 2023-02-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0205_auto_20230224_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalplan',
            name='addon_spec',
        ),
        migrations.RemoveField(
            model_name='historicalplan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalplan',
            name='display_version',
        ),
        migrations.RemoveField(
            model_name='historicalplan',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalplan',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='historicalplan',
            name='parent_plan',
        ),
        migrations.RemoveField(
            model_name='historicalplan',
            name='parent_product',
        ),
        migrations.RemoveField(
            model_name='historicalplan',
            name='target_customer',
        ),
        migrations.RemoveIndex(
            model_name='plantemplate',
            name='metering_bi_organiz_b5d6d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='plantemplate',
            name='metering_bi_organiz_5f4b15_idx',
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='plan_name',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='plantemplate',
            index=models.Index(fields=['organization', 'status'], name='metering_bi_organiz_2c8e92_idx'),
        ),
        migrations.AddIndex(
            model_name='plantemplate',
            index=models.Index(fields=['organization', 'plan_id'], name='metering_bi_organiz_659e0d_idx'),
        ),
        migrations.DeleteModel(
            name='HistoricalPlan',
        ),
    ]
