# Generated by Django 4.0.5 on 2023-02-24 20:43

from django.db import migrations


def transfer_custom_plans(apps, schema_editor):
    PlanTemplate = apps.get_model("metering_billing", "PlanTemplate")

    for plan_template in PlanTemplate.objects.filter(target_customer__isnull=True):
        parent_template = plan_template.parent_plan
        num_versions_in_parent = parent_template.versions.count()
        i = 1
        for version in plan_template.versions.all():
            version.version = num_versions_in_parent + i
            version.plan = parent_template
            version.customers.add(plan_template.target_customer)
            version.is_custom = True
            version.save()
            i += 1
    PlanTemplate.objects.filter(target_customer__isnull=True).delete()


def set_not_before(apps, schema_editor):
    PlanTemplate = apps.get_model("metering_billing", "PlanTemplate")
    for template in PlanTemplate.objects.all():
        if template.created_on:
            template.not_active_before = template.created_on
            template.save()


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0206_remove_historicalplan_addon_spec_and_more"),
    ]

    operations = [
        migrations.RunPython(transfer_custom_plans),
        migrations.RunPython(set_not_before),
    ]
