# Generated by Django 4.0.5 on 2023-02-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0209_transfer_addon_spec"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantemplate",
            name="addon_spec",
        ),
        migrations.AlterField(
            model_name="plantemplate",
            name="plan_duration",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                ],
                default="monthly",
                help_text="Duration of the plan",
                max_length=40,
            ),
        ),
    ]
