# Generated by Django 4.0.5 on 2023-02-24 21:23

from django.db import migrations


def populate_features_and_metrics(apps, schema_editor):
    PlanTemplate = apps.get_model("metering_billing", "PlanTemplate")
    for plan_template in PlanTemplate.objects.all():
        for plan_version in plan_template.versions.all():
            for feature in plan_version.features.all():
                plan_template.features.add(feature)
            for pc in plan_version.plan_components.all():
                plan_template.metrics.add(pc.billable_metric)


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0210_remove_plantemplate_addon_spec_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_features_and_metrics),
    ]
