# Generated by Django 4.0.5 on 2023-02-24 21:35

from django.db import migrations, models
import metering_billing.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0210_remove_plantemplate_addon_spec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplanversion',
            name='not_active_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalplanversion',
            name='not_active_before',
            field=models.DateTimeField(blank=True, default=metering_billing.utils.utils.now_utc),
        ),
        migrations.AddField(
            model_name='planversion',
            name='not_active_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planversion',
            name='not_active_before',
            field=models.DateTimeField(blank=True, default=metering_billing.utils.utils.now_utc),
        ),
    ]
