# Generated by Django 4.0.5 on 2023-02-24 21:35

from django.db import migrations


def set_not_before(apps, schema_editor):
    PlanVersion = apps.get_model("metering_billing", "PlanVersion")
    for version in PlanVersion.objects.all():
        if version.created_on:
            version.not_active_before = version.created_on
            version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0211_historicalplanversion_not_active_after_and_more"),
    ]

    operations = [
        migrations.RunPython(set_not_before),
    ]
