# Generated by Django 4.0.5 on 2023-02-24 21:40

from django.db import migrations, models


def transfer_plan_duration_from_template(apps, schema_editor):
    PlanVersion = apps.get_model("metering_billing", "PlanVersion")
    for version in PlanVersion.objects.all():
        version.plan_duration = version.plan.plan_duration
        version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0212_set_nbf_on_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalplanversion",
            name="plan_duration",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                ],
                default="monthly",
                help_text="Duration of the plan",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="planversion",
            name="plan_duration",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                ],
                default="monthly",
                help_text="Duration of the plan",
                max_length=40,
            ),
        ),
        migrations.RunPython(transfer_plan_duration_from_template),
    ]
