# Generated by Django 4.0.5 on 2023-02-24 21:48

from django.db import migrations


def set_not_after(apps, schema_editor):
    from metering_billing.utils import now_utc

    PlanVersion = apps.get_model("metering_billing", "PlanVersion")
    for version in PlanVersion.objects.all():
        if version.status == "active":
            version.not_active_after = None
        else:
            version.not_active_after = now_utc()
        version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0213_historicalplanversion_plan_duration_and_more"),
    ]

    operations = [
        migrations.RunPython(set_not_after),
    ]
