# Generated by Django 4.0.5 on 2023-02-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0214_change_not_after'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalplanversion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalplanversion',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalplanversion',
            name='transition_to',
        ),
        migrations.RemoveField(
            model_name='historicalplanversion',
            name='usage_billing_frequency',
        ),
        migrations.RemoveField(
            model_name='plantemplate',
            name='plan_duration',
        ),
        migrations.RemoveField(
            model_name='planversion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='planversion',
            name='status',
        ),
        migrations.RemoveField(
            model_name='planversion',
            name='transition_to',
        ),
        migrations.RemoveField(
            model_name='planversion',
            name='usage_billing_frequency',
        ),
        migrations.AddField(
            model_name='historicalplanversion',
            name='name_override',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='planversion',
            name='name_override',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
