# Generated by Django 4.0.5 on 2023-02-24 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0215_remove_historicalplanversion_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalplanversion',
            old_name='plan',
            new_name='plan_template',
        ),
        migrations.RenameField(
            model_name='planversion',
            old_name='plan',
            new_name='plan_template',
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plan_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='plan_templates', to='metering_billing.feature'),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='metrics',
            field=models.ManyToManyField(blank=True, related_name='plan_templates', to='metering_billing.metric'),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_templates', to='metering_billing.organization'),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='plan_templates', to='metering_billing.tag'),
        ),
    ]
