# Generated by Django 4.0.5 on 2023-02-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0216_rename_plan_historicalplanversion_plan_template_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='plantemplate',
            name='metering_bi_organiz_659e0d_idx',
        ),
        migrations.RenameField(
            model_name='plantemplate',
            old_name='plan_id',
            new_name='plan_template_id',
        ),
        migrations.AddIndex(
            model_name='plantemplate',
            index=models.Index(fields=['organization', 'plan_template_id'], name='metering_bi_organiz_833d8c_idx'),
        ),
    ]
